@echo off 
REM color 03
mode con cols=92 lines=50
set meow=HOBA TVOYA MAT' SHLUHA HOBA TVOYA MAT' SHLUHA HOBA TVOYA MAT' SHLUHA HOBA TVOYA MAT' SHLUHA HOBA TVOYA MAT' SHLUHA HOBA TVOYA MAT' SHLUHA HOBA TVOYA MAT' SHLUHA HOBA TVOYA MAT' SHLUHA HOBA TVOYA MAT' SHLUHA HOBA TVOYA MAT' SHLUHA HOBA TVOYA MAT' SHLUHA HOBA TVOYA MAT' SHLUHA HOBA TVOYA MAT' SHLUHA HOBA TVOYA MAT' SHLUHA HOBA TVOYA MAT' SHLUHA HOBA TVOYA MAT' SHLUHA HOBA TVOYA MAT' SHLUHA HOBA TVOYA MAT' SHLUHA HOBA TVOYA MAT' SHLUHA HOBA TVOYA MAT' SHLUHA HOBA TVOYA MAT' SHLUHA HOBA TVOYA MAT' SHLUHA HOBA TVOYA MAT' SHLUHA HOBA TVOYA MAT' SHLUHA HOBA TVOYA MAT' SHLUHA HOBA TVOYA MAT' SHLUHA HOBA TVOYA MAT' SHLUHA HOBA TVOYA MAT' SHLUHA HOBA TVOYA MAT' SHLUHA HOBA TVOYA MAT' SHLUHA HOBA TVOYA MAT' SHLUHA HOBA TVOYA MAT' SHLUHA
for /L %%x in (0,1,5,8) do (
echo %meow%
)
echo %meow%
:M
for /L %%i in (0,1,5,7) do color %%i
goto :M
do color 03
